<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title>MyParcel - Magento - Passdata from PostNL through MyParcel</title>
</head>
<body>
<script type="text/javascript">
/* Querystring.js ******************************************************************************/
    function Querystring(qs) { // optionally pass a querystring to parse
        this.params = new Object()
        this.get=Querystring_get

        if (qs == null)
            qs=location.search.substring(1,location.search.length)

        if (qs.length == 0) return

        qs = qs.replace(/\+/g, ' ')
        var args = qs.split('&') // parse out name/value pairs separated via &


        for (var i=0;i<args.length;i++) {
            var value;
            var pair = args[i].split('=')
            var name = unescape(pair[0])

            if (pair.length == 2)
                value = unescape(pair[1])
            else
                value = name

            this.params[name] = value
        }
    }

    function Querystring_get(key, default_) {
        // This silly looking line changes UNDEFINED to NULL
        if (default_ == null) default_ = null;

        var value=this.params[key]
        if (value==null) value=default_;

        return value
    }

    window.onload = passData;
    function passData()
    {
        var name;
        var street;
        var houseNr;
        var houseNrAdd;
        var postalCodeNum;
        var postalCodeAlpha;
        var city;

        var qs = new Querystring();
        if (qs.get("action") == "confirm")
        {
            name            = qs.get('name');
            street          = qs.get('street');
            houseNr         = qs.get('housenumber');
            houseNrAdd      = qs.get('housenumberadd');
            postalCodeNum   = qs.get('postalcodenum');
            postalCodeAlpha = qs.get('postalcodealpha');
            city            = qs.get('city');

            if(parent.parent.window.opener)
            {
                var shopname = name.split('&nbsp;&nbsp;');
                if(shopname.length == 2) shopname = shopname[1];

                parent.parent.window.opener.myParcelPgAddress.setAddress({
                    name           : shopname,
                    street         : street,
                    housenumber    : houseNr,
                    housenumberadd : houseNrAdd,
                    postalcode     : postalCodeNum + postalCodeAlpha,
                    city           : city,
                    country        : 'NL',
                }).updateFieldset();
            }
        }
        parent.parent.window.close();
    }
</script>
</body>
</html>